"""add architect_sessions.drawdown_acknowledged_at

Revision ID: 824985a93d1d
Revises: e45a69fcda1e
Create Date: 2026-05-02 18:15:12.096184

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '824985a93d1d'
down_revision: Union[str, None] = 'e45a69fcda1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('architect_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drawdown_acknowledged_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('architect_sessions', schema=None) as batch_op:
        batch_op.drop_column('drawdown_acknowledged_at')

    # ### end Alembic commands ###
