"""initial_schema

Revision ID: eaf2e2700b46
Revises: 
Create Date: 2026-04-26 18:52:46.031360

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eaf2e2700b46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('etf_scores_cache',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('cost_score', sa.Float(), nullable=True),
    sa.Column('sharpe_score', sa.Float(), nullable=True),
    sa.Column('tracking_error_score', sa.Float(), nullable=True),
    sa.Column('liquidity_score', sa.Float(), nullable=True),
    sa.Column('components_json', sa.Text(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('goal_buckets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('horizon_type', sa.String(length=10), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal_buckets', schema=None) as batch_op:
        batch_op.create_index('idx_buckets_archived', ['is_archived'], unique=False)
        batch_op.create_index('idx_buckets_horizon', ['horizon_type'], unique=False)

    op.create_table('macro_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'date', name='uq_macro_series_date')
    )
    with op.batch_alter_table('macro_data', schema=None) as batch_op:
        batch_op.create_index('idx_macro_series_date', ['series_id', 'date'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close_usd', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'date', name='uq_price_ticker_date')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index('idx_prices_ticker_date', ['ticker', 'date'], unique=False)

    op.create_table('sector_cache',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('sector_weights_json', sa.Text(), nullable=False),
    sa.Column('top_holdings_json', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    with op.batch_alter_table('sector_cache', schema=None) as batch_op:
        batch_op.create_index('idx_sector_cache_expires', ['expires_at'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('valuation_cache',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('z_score', sa.Float(), nullable=True),
    sa.Column('percentile_52w', sa.Float(), nullable=True),
    sa.Column('sma200_deviation', sa.Float(), nullable=True),
    sa.Column('classification', sa.String(length=30), nullable=True),
    sa.Column('has_3y_history', sa.Boolean(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('architect_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('selected_buckets_json', sa.Text(), nullable=True),
    sa.Column('shortlist_json', sa.Text(), nullable=True),
    sa.Column('ai_proposal_json', sa.Text(), nullable=True),
    sa.Column('final_allocation_json', sa.Text(), nullable=True),
    sa.Column('rationale_text', sa.Text(), nullable=True),
    sa.Column('sector_report_json', sa.Text(), nullable=True),
    sa.Column('drawdown_report_json', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['goal_buckets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deposit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('fx_rate', sa.Float(), nullable=True),
    sa.Column('orders_json', sa.Text(), nullable=False),
    sa.Column('portfolio_snapshot_json', sa.Text(), nullable=True),
    sa.Column('obsidian_file_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['goal_buckets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deposit_log', schema=None) as batch_op:
        batch_op.create_index('idx_deposits_bucket_date', ['bucket_id', 'created_at'], unique=False)

    op.create_table('drawdown_simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.Column('allocation_json', sa.Text(), nullable=False),
    sa.Column('portfolio_value_at_simulation', sa.Float(), nullable=True),
    sa.Column('portfolio_currency', sa.String(length=3), nullable=True),
    sa.Column('scenarios_json', sa.Text(), nullable=False),
    sa.Column('worst_case_pct', sa.Float(), nullable=True),
    sa.Column('worst_case_amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['goal_buckets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('avg_cost_usd', sa.Float(), nullable=True),
    sa.Column('target_pct', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['goal_buckets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_id', 'ticker', name='uq_holdings_bucket_ticker')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index('idx_holdings_bucket', ['bucket_id'], unique=False)
        batch_op.create_index('idx_holdings_ticker', ['ticker'], unique=False)

    op.create_table('pending_actions',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('bucket_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bucket_id'], ['goal_buckets.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pending_actions')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index('idx_holdings_ticker')
        batch_op.drop_index('idx_holdings_bucket')

    op.drop_table('holdings')
    op.drop_table('drawdown_simulations')
    with op.batch_alter_table('deposit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_deposits_bucket_date')

    op.drop_table('deposit_log')
    op.drop_table('architect_sessions')
    op.drop_table('valuation_cache')
    op.drop_table('settings')
    with op.batch_alter_table('sector_cache', schema=None) as batch_op:
        batch_op.drop_index('idx_sector_cache_expires')

    op.drop_table('sector_cache')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('idx_prices_ticker_date')

    op.drop_table('price_history')
    with op.batch_alter_table('macro_data', schema=None) as batch_op:
        batch_op.drop_index('idx_macro_series_date')

    op.drop_table('macro_data')
    with op.batch_alter_table('goal_buckets', schema=None) as batch_op:
        batch_op.drop_index('idx_buckets_horizon')
        batch_op.drop_index('idx_buckets_archived')

    op.drop_table('goal_buckets')
    op.drop_table('etf_scores_cache')
    # ### end Alembic commands ###
