"""Terms-of-use text and version registry.

Bumping TERMS_VERSION forces every existing user to re-accept on next login.
The hash is computed from the EN+HE text together so we have an immutable
fingerprint of *exactly* what each user agreed to.
"""
from __future__ import annotations

import hashlib

TERMS_VERSION = "1.0.0"
TERMS_EFFECTIVE_DATE = "2026-05-04"


TERMS_EN = """\
TERMS OF USE AND DISCLAIMER
Effective date: 2026-05-04
Version: 1.0.0

By creating an account, accessing, or using the IQ Invest ETF software (the
"Software"), you acknowledge that you have read, understood, and agree to be
bound by these Terms of Use and Disclaimer (the "Terms"). If you do not agree,
do not create an account and do not use the Software.

1. NO INVESTMENT ADVICE
   The Software is provided strictly for personal, educational, informational,
   analytical, and research purposes. NOTHING in the Software constitutes
   investment advice, financial advice, tax advice, legal advice, accounting
   advice, a recommendation, an offer, or a solicitation to buy, sell, or hold
   any security, ETF, fund, derivative, currency, commodity, or any other
   financial instrument. Any output, score, ranking, valuation, simulation,
   suggestion, allocation, deposit plan, drawdown projection, sector
   exposure analysis, or other content generated by the Software is provided
   "as is" for your private review only.

2. NOT A LICENSED PROFESSIONAL
   The operator and developer of the Software is NOT a licensed investment
   advisor, portfolio manager, broker, financial planner, or any other regulated
   financial professional under Israeli law (Regulation of Investment Advice,
   Investment Marketing, and Portfolio Management Law, 5755-1995) or under any
   other jurisdiction. The operator does not hold any license, registration, or
   authorization to provide investment advice or to manage portfolios on behalf
   of others. No fiduciary, advisory, or client relationship is created between
   you and the operator by your use of the Software.

3. YOUR SOLE RESPONSIBILITY
   You are solely and exclusively responsible for: (a) every investment,
   trading, deposit, allocation, rebalancing, or financial decision you make;
   (b) verifying the accuracy and current relevance of any data shown by the
   Software with primary sources before acting; (c) consulting a properly
   licensed investment advisor, tax advisor, accountant, or attorney before
   making any financial decision; (d) understanding the risks of investing,
   including the risk of partial or total loss of capital; (e) all tax
   reporting and tax obligations arising from your investment activity.

4. NO WARRANTIES; DATA MAY BE INACCURATE OR STALE
   The Software relies on third-party data sources (including but not limited
   to yfinance, FRED, ETF issuers' published metadata, and AI-generated
   content) which may be delayed, inaccurate, incomplete, stale, or subject to
   change without notice. ETF metadata, prices, expense ratios, AUM, holdings,
   sector exposures, dividends, and historical returns are provided WITHOUT
   ANY WARRANTY of accuracy, completeness, fitness for a particular purpose,
   timeliness, or non-infringement. The Software is provided "AS IS" and "AS
   AVAILABLE."

5. PAST PERFORMANCE
   Past performance, historical drawdowns, simulated returns, backtests,
   correlation matrices, and valuation metrics do not guarantee, predict, or
   imply any future performance. Markets can move in ways that no historical
   model anticipates.

6. AI-GENERATED CONTENT
   The Software may generate prompts to be used with third-party AI services
   (such as OpenAI ChatGPT or Anthropic Claude) and may ingest JSON output
   from such services. AI output may be incorrect, hallucinated, biased, or
   unsuitable. You must independently verify any AI-generated suggestion
   before relying on it.

7. LIMITATION OF LIABILITY
   To the maximum extent permitted by applicable law, in no event shall the
   operator, developer, or any contributor be liable for any direct, indirect,
   incidental, special, consequential, exemplary, or punitive damages,
   including but not limited to loss of profits, loss of capital, loss of
   data, or loss of goodwill, arising out of or in connection with your use
   of, or inability to use, the Software, even if advised of the possibility
   of such damages. Your sole remedy for dissatisfaction with the Software is
   to stop using it.

8. ACCOUNT SECURITY
   You are responsible for safeguarding your account credentials, including
   your password and any access tokens. You must notify the operator
   immediately of any unauthorized access. The operator is not liable for any
   loss arising from unauthorized access caused by your failure to safeguard
   your credentials.

9. ACCEPTABLE USE
   You agree not to: (a) use the Software for any unlawful purpose; (b)
   attempt to reverse-engineer, decompile, or disassemble the Software except
   to the extent permitted by applicable law; (c) circumvent any technical
   limitation; (d) use the Software to provide investment advice or portfolio
   management services to third parties; (e) re-distribute the Software's
   output as your own professional analysis.

10. PRIVACY
    The Software stores your account information (email, full name, hashed
    password) and your portfolio data locally and on the operator's servers
    as needed to provide the service. The operator does not sell your
    personal data. The operator may collect anonymous usage telemetry to
    improve the Software.

11. CHANGES TO THESE TERMS
    These Terms may be updated from time to time. When the version changes,
    you will be required to re-accept the updated Terms on your next login.
    Continued use of the Software after a Terms update constitutes acceptance
    of the new Terms.

12. TERMINATION
    You may stop using the Software and delete your account at any time. The
    operator may suspend or terminate accounts that violate these Terms.

13. GOVERNING LAW AND JURISDICTION
    These Terms are governed by the laws of the State of Israel, without
    regard to its conflict-of-laws principles. Any dispute arising out of or
    relating to these Terms or the Software shall be subject to the exclusive
    jurisdiction of the competent courts in Tel Aviv-Yafo, Israel.

14. SEVERABILITY
    If any provision of these Terms is held to be unenforceable, the
    remaining provisions shall remain in full force and effect.

15. ENTIRE AGREEMENT
    These Terms constitute the entire agreement between you and the operator
    regarding the Software and supersede any prior agreements.

BY CLICKING "I AGREE" OR BY USING THE SOFTWARE, YOU CONFIRM THAT YOU HAVE
READ, UNDERSTOOD, AND ACCEPTED THESE TERMS.
"""


TERMS_HE = """\
תנאי שימוש וכתב ויתור
תאריך תחילה: 04/05/2026
גרסה: 1.0.0

ביצירת חשבון, גישה או שימוש בתוכנת IQ Invest ETF ("התוכנה") אתה מאשר כי קראת,
הבנת והסכמת להיות מחויב בתנאי שימוש וכתב ויתור אלה ("התנאים"). אם אינך מסכים,
אל תיצור חשבון ואל תשתמש בתוכנה.

1. אין במידע משום ייעוץ השקעות
   התוכנה מסופקת אך ורק למטרות אישיות, חינוכיות, מידעיות, אנליטיות ומחקריות.
   שום דבר בתוכנה אינו מהווה ייעוץ השקעות, ייעוץ פיננסי, ייעוץ מס, ייעוץ משפטי,
   ייעוץ חשבונאי, המלצה, הצעה או שידול לקנות, למכור או להחזיק נייר ערך, תעודת
   סל, קרן, נגזר, מטבע, סחורה או כל מכשיר פיננסי אחר. כל פלט, ציון, דירוג,
   ולואציה, סימולציה, הצעה, הקצאה, תוכנית הפקדה, תחזית מפולת, ניתוח חשיפה
   סקטוריאלית או תוכן אחר שמופק על ידי התוכנה — מסופק "כפי שהוא" (AS IS) לעיון
   פרטי בלבד.

2. לא בעל רישיון מקצועי
   המפעיל והמפתח של התוכנה אינו יועץ השקעות מורשה, מנהל תיקי השקעות, סוחר ני"ע,
   מתכנן פיננסי או כל בעל מקצוע פיננסי מפוקח אחר על פי דין ישראלי (חוק הסדרת
   העיסוק בייעוץ השקעות, בשיווק השקעות ובניהול תיקי השקעות, התשנ"ה-1995) או
   בכל סמכות שיפוט אחרת. המפעיל אינו מחזיק ברישיון, רישום או אישור כלשהם
   לספק ייעוץ השקעות או לנהל תיקים בעבור אחרים. שימושך בתוכנה אינו יוצר
   יחסי אמון, ייעוץ או לקוח-יועץ בינך ובין המפעיל.

3. אחריותך הבלעדית
   אתה אחראי באופן בלעדי ומלא ל: (א) כל החלטה השקעתית, מסחרית, הפקדה, הקצאה,
   איזון מחדש או החלטה פיננסית שתקבל; (ב) אימות הדיוק והרלוונטיות העדכנית של
   כל נתון המוצג בתוכנה מול מקורות ראשוניים בטרם פעולה; (ג) התייעצות עם יועץ
   השקעות מורשה כדין, יועץ מס, רואה חשבון או עורך דין בטרם קבלת כל החלטה
   פיננסית; (ד) הבנת סיכוני ההשקעה, לרבות הסיכון להפסד חלקי או מלא של ההון;
   (ה) כל דיווח מס וחבות מס הנובעים מפעילותך ההשקעתית.

4. ללא אחריות; הנתונים עשויים להיות שגויים או לא מעודכנים
   התוכנה מסתמכת על מקורות נתונים של צדדים שלישיים (לרבות yfinance, FRED,
   מטא-דאטה שמפרסמות חברות תעודות הסל, ותכנים שנוצרים על ידי AI) שעשויים להיות
   מעוכבים, שגויים, חלקיים, ישנים או נתונים לשינוי ללא הודעה מוקדמת. מטא-דאטה
   של תעודות סל, מחירים, דמי ניהול, AUM, אחזקות, חשיפות סקטוריאליות, דיבידנדים
   ותשואות היסטוריות — מסופקים ללא כל אחריות לדיוק, שלמות, התאמה למטרה
   ספציפית, עדכניות או אי-הפרה. התוכנה מסופקת "כפי שהיא" ו"כפי שזמינה".

5. ביצועי עבר
   ביצועי עבר, מפולות היסטוריות, תשואות מסומלצות, backtests, מטריצות קורלציה
   ומדדי ולואציה — אינם מבטיחים, חוזים או רומזים על ביצועים עתידיים. השווקים
   עשויים לנוע באופן ששום מודל היסטורי אינו צופה.

6. תוכן שנוצר על ידי AI
   התוכנה עשויה לייצר פרומפטים לשימוש בשירותי AI של צדדים שלישיים (כגון
   OpenAI ChatGPT או Anthropic Claude) ולקלוט פלט JSON מהשירותים הללו. פלט AI
   עשוי להיות שגוי, מומצא ("הזיה"), מוטה או לא מתאים. עליך לוודא באופן עצמאי
   כל הצעת AI לפני שתסתמך עליה.

7. הגבלת אחריות
   במידה המרבית המותרת על פי הדין החל, בשום מקרה לא יהיו המפעיל, המפתח או כל
   תורם אחר אחראים לכל נזק ישיר, עקיף, מקרי, מיוחד, תוצאתי, לדוגמה או עונשי,
   לרבות אך לא רק אובדן רווחים, אובדן הון, אובדן נתונים או אובדן מוניטין —
   הנובעים מהשימוש שלך בתוכנה או מאי-יכולתך להשתמש בה, גם אם הוזהרת על אפשרות
   נזקים כאמור. הסעד היחיד שלך במקרה של חוסר שביעות רצון מהתוכנה הוא להפסיק
   להשתמש בה.

8. אבטחת חשבון
   אתה אחראי על שמירת אישורי החשבון שלך, לרבות הסיסמה וכל אסימון גישה. עליך
   להודיע למפעיל מיד על כל גישה לא מורשית. המפעיל אינו אחראי על אובדן הנובע
   מגישה לא מורשית שנגרמה כתוצאה מאי-שמירה על אישוריך.

9. שימוש מותר
   אתה מתחייב שלא: (א) להשתמש בתוכנה למטרה לא חוקית; (ב) לנסות לבצע הנדסה
   לאחור, decompilation או disassembly של התוכנה למעט במידה המותרת על פי דין;
   (ג) לעקוף מגבלה טכנית כלשהי; (ד) להשתמש בתוכנה כדי לספק ייעוץ השקעות או
   שירותי ניהול תיקים לצדדים שלישיים; (ה) להפיץ את פלט התוכנה כניתוח מקצועי
   עצמאי שלך.

10. פרטיות
    התוכנה שומרת את פרטי החשבון שלך (אימייל, שם מלא, hash של סיסמה) ואת נתוני
    התיק שלך באופן מקומי ובשרתי המפעיל ככל הנדרש לאספקת השירות. המפעיל אינו
    מוכר את הנתונים האישיים שלך. המפעיל עשוי לאסוף טלמטריית שימוש אנונימית
    לצורך שיפור התוכנה.

11. שינויים בתנאים
    התנאים הללו עשויים להתעדכן מעת לעת. כאשר הגרסה משתנה, תידרש לאשר מחדש את
    התנאים המעודכנים בכניסתך הבאה. שימוש מתמשך בתוכנה לאחר עדכון התנאים מהווה
    הסכמה לתנאים החדשים.

12. הפסקת שימוש
    אתה רשאי להפסיק להשתמש בתוכנה ולמחוק את חשבונך בכל עת. המפעיל רשאי להשעות
    או לסיים חשבונות המפרים את התנאים הללו.

13. הדין החל וסמכות שיפוט
    תנאים אלה כפופים לדיני מדינת ישראל, ללא התחשבות בכללי ברירת הדין שלה. כל
    מחלוקת הנובעת או קשורה לתנאים אלה או לתוכנה תהיה בסמכותם הייחודית של בתי
    המשפט המוסמכים בתל-אביב-יפו, ישראל.

14. נפרדות הוראות
    אם הוראה כלשהי בתנאים אלה תיקבע כבלתי ניתנת לאכיפה, יתר ההוראות יישארו
    בתוקפן המלא.

15. הסכם שלם
    תנאים אלה מהווים את ההסכם השלם בינך ובין המפעיל בנוגע לתוכנה ובאים במקום
    כל הסכם קודם.

בלחיצה על "אני מסכים/ה" או בשימוש בתוכנה, אתה מאשר/ת כי קראת, הבנת והסכמת
לתנאים אלה.
"""


def compute_terms_hash() -> str:
    """SHA-256 of the concatenated EN+HE text — immutable fingerprint of
    exactly what the user accepted at this version."""
    payload = f"{TERMS_VERSION}\n{TERMS_EN}\n---\n{TERMS_HE}".encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


TERMS_HASH = compute_terms_hash()
